### ISSUE TITLE
Maybe put instance in parameter instead of path

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-cloudflare-worker#103]
Currently we have to take care not to prefix special paths (like `/auth/…` or `/api/…`) with the instance, like we do for most other links. 

**Idea:**
Maybe we could always put the instance in an query string instead (`e.g. ?instance=de`) this way it would just be ignored for special paths instead of breaking everything.

**Comment by inyono** [comment]
In contrast to a query string, the instance in the path can be resolved statically (i.e. at compile-time vs. at run-time). This might be a requirement for a i18n library (which we should include at some point). For example, [`next-translate`](https://github.com/vinissimus/next-translate) creates the pages for each language at compile-time. Not sure how i18n added to Next.js v10.0.0 works, there it might also be a requirement to have the information at compile-time.

IMHO: we should have a plan for how to handle i18n in the future (e.g. with a library) before we change the approach.

**Comment by elbotho** [comment]
@inyono i def. agree with your conclusion 👍 

Not sure about the first part. It was my understanding, that the query string is also part of a static url (in contrast to e.g. the fragment identifier/hash).
