### ISSUE TITLE
Dev & Staging: Add password protection

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#139]
In dev & staging legacy serlo.org is password protected. This is not the case for the new design. Thus we need a way to protect the whole environment with a password. Alternative: Add a `/robots.txt` which excludes all dev & staging domains.

**Comment by inyono** [comment]
Not needed, since Vercel already sets the correct headers for non-production deploys.

**Comment by kulla** [comment]
> Not needed, since Vercel already sets the correct meta tags for non-production deploys.

Do we want to have a general password protection in dev / staging or is it just so that search engine crawler do not index the sites?

**Comment by inyono** [comment]
The latter.

**Comment by kulla** [comment]
Okay :+1:
