### ISSUE TITLE
Follow-Up discussion for #128 (embed.serlo.org)

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#145]
- [ ] Shall the TaskEither Monad be used: https://github.com/serlo/serlo.org-cloudflare-worker/blob/5e7e8fe887674b46c1b59699b4c38653f0451414/src/embed.ts#L99-L123
- [ ] Shall the url returned by vimeo or geogebra api be checked: https://github.com/serlo/serlo.org-cloudflare-worker/blob/5e7e8fe887674b46c1b59699b4c38653f0451414/src/embed.ts#L164-L166

**Comment by kulla** [comment]
@elbotho Can you check whether I missed something?

**Comment by elbotho** [comment]
Look good, thanks!

**Comment by elbotho** [comment]
Dev-Meet:
- TaskEither Monad: probably easier to use try… catch… and set type to unknown
- Test: Probably enough/better to check if result is image

**Comment by kulla** [comment]
implemented by https://github.com/serlo/serlo.org-cloudflare-worker/pull/154
