### ISSUE TITLE
Sometimes, language subpath is accessed

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#153]
In some cases (~100 times in the last 4 days), users land on a page with language subpath, e.g. `https://de.serlo.org/de/mathe/1324/exponential-und-logarithmusfunktion`.

Maybe we can find a way to reproduce this bug.

**Comment by kulla** [comment]
Yeah, I guess it's an issue with the CF since adding the language prefix happens while redirecting to the frontend. It seems that this is an edge case where the frontend url is created without usind the frontend backend. I need to investigate it. @Entkenntnis Thx for reporting, I have transfered the issue to the CF repo.

**Comment by Entkenntnis** [comment]
@kulla Currently, if I try to access `de.serlo-staging.dev`, I get a 308 permanent redirect to `https://frontend-git-staging-serlo.vercel.app/de` (tried with every browser I have) - this is confirming that the cf worker has situations where the proxy is behaving as a redirect.

**Comment by kulla** [comment]
> @kulla Currently, if I try to access `de.serlo-staging.dev`, I get a 308 permanent redirect to `https://frontend-git-staging-serlo.vercel.app/de` (tried with every browser I have) - this is confirming that the cf worker has situations where the proxy is behaving as a redirect.

This is due to the fact that the frontend domain in staging has changed (see fix https://github.com/serlo/serlo.org-cloudflare-worker/pull/172/files which is already deployed). Is this intentually? I doubt, that this is the bug reporting in this issue so more investigation is needed.

**Comment by Entkenntnis** [comment]
Good to know that the domain has changed - didn't noticed this yet. Unfortunate that this is passed forward to the client.

**Comment by kulla** [comment]
@elbotho Does this bug occur sometimes? Otherwise I would close this issue...

**Comment by elbotho** [comment]
Could not find any occurrences in simple analytics in the last month.
