### ISSUE TITLE
Handle /___graphql via frontend

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-cloudflare-worker#161]
https://frontend.serlo.org/___graphql can be used to do api requests with your user token. It throws an 404 at serlo-staging.dev and serlo.org, though, since CF worker handles it via legacy system.

**Comment by kulla** [comment]
You mean, `*.serlo.org/___graphql` should **always** be redirected to the new frontend or only when the user is in the group which should be redirected to the new frontend?

**Comment by inyono** [comment]
Always since this isn't handled by legacy serlo.org in any way.

**Comment by kulla** [comment]
@inyono Done: https://de.serlo.org/___graphql
