### ISSUE TITLE
Handle redirects of the frontend

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#173]
There should never be a redirect of the frontend. However in case of change or in not programmed edge case this might occur (see https://github.com/serlo/serlo.org-cloudflare-worker/issues/153#issuecomment-783307475 ). Therefore:

- [ ] Follow redirects of the frontend so that we have a "safety net"
- [ ] Report this to Sentry (maybe only once an hour)

**Comment by inyono** [comment]
> There should never be a redirect of the frontend

What do you mean by this?

**Comment by kulla** [comment]
> What do you mean by this?

When CF makes a request to the frontend, the frontend should never answer with a redirect.
