### ISSUE TITLE
Redirect de.serlo.org/global to en.serlo.org/global

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org-cloudflare-worker#183]
https://en.serlo.org/93321/serlo.org-in-other-languages is the landing-page for everything language/internationalization-related. Therefore it would be amazing if serlo.org/global, or maybe more specific since serlo.org/global rerouts to de.serlo.org/global, the latter would rerout to en.serlo.org/global or https://en.serlo.org/93321/serlo.org-in-other-languages. That makes it easier to share the URL with other people.

**Comment by kulla** [comment]
Okay, then we need a redirect at CF :-)
