### ISSUE TITLE
courses with /toc unsupported

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-cloudflare-worker#184]
I don't know where they come from, but there are course-links (found via google) that end with `/toc` that are not supported in the frontend.

e.g.
https://de.serlo.org/entity/view/58362/toc

**Comment by elbotho** [comment]
when in doubt, for simplicity… 
I think we should handle them link the links to the course id: redirect to the first course page.
@kulla do you agree? Is this the right repo for this?

**Comment by Knorrke** [comment]
I think you can also just remove it. A long time ago this was used for the course view, but we don't have that anymore (redirecting to first course page instead). So I'm pretty sure it's not used anymore. Probably just overlooked that when shutting of the course overview pages.

**Comment by kulla** [comment]
A redirect is implemented (see https://github.com/serlo/serlo.org-cloudflare-worker/pull/186 ) and deployed ( https://de.serlo.org/entity/view/58362/toc now redirects to the first course page ). 

> I think you can also just remove it.

@Knorrke Thanks for your reply. I'll do it now...

**Comment by elbotho** [comment]
Nice, thank you!
