### ISSUE TITLE
POST /taxonomy/term/create/[parent]/[id] -> legacy

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#277]
after #274, the POST request is now handled by the frontend, but it should be the backend. Only relevant if this can be quickly fixed, otherwise we will use new mutation for this

**Comment by Entkenntnis** [comment]
we are already setting `X-From | legacy-serlo.org`, but this seems to have no effect?

**Comment by kulla** [comment]
> after https://github.com/serlo/serlo.org-cloudflare-worker/issues/274, the POST request is now handled by the frontend, but it should be the backend. Only relevant if this can be quickly fixed, otherwise we will use new mutation for this

you want the GET-request for the frontend and the POST-request to the legacy backend, right?
