### ISSUE TITLE
page revisions not working

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#290]
Visit: https://de.serlo.org/entity/repository/history/18922

Opening a page revision in a new tab (e.g. without csr), the url is rewritten to `<revisionID>/<title>`, which is not supported. It should not redirect a url like https://de.serlo.org/entity/repository/compare/18922/244951 (the frontend can handle this)

not urgent, as page revision support will probably be removed ...

**Comment by kulla** [comment]
Superseaded by https://github.com/serlo/serlo.org-database-layer/issues/325

**Comment by elbotho** [comment]
@kulla sorry, did not check for old issues.
