### ISSUE TITLE
Infinite redirect for page revision link

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-cloudflare-worker#299]
Links like this
`/entity/repository/compare/[repoId]/[revisionId]`
are redirected to
`/[revisionId]/[pageTitle]`
instead of
`/[repoId]/[pageTitle]`
and therefore cause an infinite loop.

CSR in the frontend works fine so it's probably a CF-worker issue.

**Comment by kulla** [comment]
Superseaded by https://github.com/serlo/serlo.org-database-layer/issues/325
