### ISSUE TITLE
Support internationalization for frontend

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#32]
- [x] add language instance as prefix to path to frontend
- [x] add redirect when current id or alias is not the current alias
- [x] redirect from course to first course page

**Comment by inyono** [comment]
Please implement the language instance as path prefix behind a feature flag.

**Comment by Entkenntnis** [comment]
There is another kind of redirect: If the entity is a Course, it should redirect to the first CoursePage. It would be cool if the cloudflare worker can take care of this, too. (because the frontend does not need to do any redirects anymore)

**Comment by kulla** [comment]
> There is another kind of redirect: If the entity is a Course, it should redirect to the first CoursePage. It would be cool if the cloudflare worker can take care of this, too. (because the frontend then does not need to do any redirects anymore)

What shall be the redirect to, when the course is empty (list of course pages is empty)? Shall it be the path to the course itself?

**Comment by Entkenntnis** [comment]
Good question, never encounted this case yet. Do you have an example? Probably a 404.

**Comment by kulla** [comment]
> Good question, never encounted this case yet. Do you have an example? Probably a 404.

Puh, there might be no example yet. I just encounter this during implementing this since I need a behavior when the list of course pages is empty.

**Comment by kulla** [comment]
> Good question, never encounted this case yet. Do you have an example? Probably a 404.

I had a look into the database. Currently there is no course without a course page. I am also not sure whether you can create such a course currently -> what would happen in the frontend, when an course without a course page would be opend?

**Comment by inyono** [comment]
Currently, there shouldn't be a way to create such a course but there might be legacy courses in production db without course pages.

To recreate such a course locally:
- Create a course
- Save it
- Go to the first course page
- Trash the first course page (and possibly purge)
