### ISSUE TITLE
frontend-proxy: regressions

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-cloudflare-worker#40]
Master has regressions in the fronted proxy (compare de.serlo-development.dev (master) with de.serlo-staging.dev (previous working version)), e.g.:
- [ ] https://de.serlo-development.dev/mathe uses old frontend even when frontend is enabled.

When trying it out in staging, I also got various flashing content / Karmilla font didn't work. Can't reproduce on dev, though, so might be caching issues.

**Comment by kulla** [comment]
@inyono The type `Entity` was renamed to `AbstractEntity` in the meanwhile. :-) See #41 for the fix
