### ISSUE TITLE
Update node-fetch to 3.0

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#58]
We can update node-fetch to 3.0. Since it is only used as a dev dependency, it is okay when node fetch is still beta Then we can delete the lines https://github.com/serlo/serlo.org-cloudflare-worker/blob/d587a3ecfca13e7d123dbb5d5b7136d1289d2aab/jest.setup.ts#L89-L94

**Comment by inyono** [comment]
Is there any reason to update to 3.0 beta (instead of the current 2.x stable release)?

**Comment by kulla** [comment]
> Is there any reason to update to 3.0 beta (instead of the current 2.x stable release)?

The lines https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/jest.setup.ts#L68-L73 can be deleted :smile:

**Comment by inyono** [comment]
I see. Then I don't care either way :)

**Comment by kulla** [comment]
> I see. Then I don't mind either way :)

Let's have it as a `good first issue` task for new software developer.
