### ISSUE TITLE
Add redirects for dev-Calls

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#60]
Similar to `start.serlo.org` we want to support redirects from `meet.serlo.org` to our Serlo-Calls:

* http://meet.serlo.org/ shall redirect to https://meet.google.com/vtk-ncrc-rdp
* http://meet.serlo.org/dev shall redirect to https://meet.google.com/rci-pize-jow

Example code can be found at https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/index.ts#L70-L84

**Comment by Wei-J-Huang** [comment]
Hi, could you provide instructions on how to run/test the app locally please? Thanks!

**Comment by kulla** [comment]
> Hi, could you provide instructions on how to run/test the app locally please? Thanks!

Are you interested in solving this issue? This would be great :smile: For development you do the following:

1. After cloning the repo you run `yarn` to install all dependencies
2. With `yarn test` you can run all unit tests. We develop test-driven -> First write a test and then add source code until the tests pass.
3. Make a Pull Request

This repo contains the cloudflare worker for serlo.org Thus running the cloudflare worker locally is not easy. There is a tool ( https://developers.cloudflare.com/workers/cli-wrangler/commands#dev ) but the last time I used it, it was buggy. I can test the feature after you made the PR.

**Comment by kulla** [comment]
Fixed by https://github.com/serlo/serlo.org-cloudflare-worker/pull/93
