### ISSUE TITLE
Frontend: Allow type User in staging

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#65]

**Comment by elbotho** [comment]
same behaviour for `/user/public` please. New frontend does not handle those differently atm.

**Comment by elbotho** [comment]
@kulla okay! 
For staging please allow type "User" to be displayed be the frontend.

After [this](https://github.com/serlo/frontend/pull/679) is merged the frontend supports these paths:
- `/user/me` 
- `/user/public`
- `/user/profile/username` 

So not additional routing/etc is be needed in the worker.

**Comment by elbotho** [comment]
`/user/profile/${username}` already works 👍

**Comment by elbotho** [comment]
Okay, it seems only `/user/me` actually get's redirected to the old frontend! 
Rest seems to work.

**Comment by kulla** [comment]
@elbotho Fixed in https://github.com/serlo/serlo.org-cloudflare-worker/pull/89 deployed in staging -> can you test it there?

**Comment by elbotho** [comment]
Very nice! Thanks you.

**Comment by kulla** [comment]
Let's wait for the code review (PR still needs to be merged) :smile:
