### ISSUE TITLE
Proxy calls for embed preview images

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-cloudflare-worker#66]
### Intro
Currently we support embeds from YouTube, Wikimedia Commons, Vimeo and Geogebra.
For privacy reasons we want to hide our users IPs from the providers until they confirm loading of the external content.

So we want the CF Worker (or maybe even the API) to make the call instead.

The frontend could either query the full video url ([example](https://www.youtube.com/watch?v=dO6Wac8kNv0)) or values for `provider` and `video id` or both. 

### Provider details

The preview image code is already implemented in [this PR](https://github.com/serlo/frontend/pull/632). (`video.tsx` and `geogebra.tsx`)
Explanations:

#### YouTube
``` tsx
const previewImageUrl = `https://i.ytimg.com/vi/${videoId}/sddefault.jpg` //might not exists -> 404
const previewImageFallbackUrl = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
```
A bit annoying that the prefered `sddefault` might result in 404, but I's still better than using the YT-API with a key and all, right?

#### Vimeo
```
 function fetchVimeoInfo() {
    void fetch(
      'https://vimeo.com/api/oembed.json?url=' + encodeURIComponent(src)
    )
      .then((res) => res.json())
      .then((data) => {
        setVimeoImg(data.thumbnail_url.replace(/_[0-9|x]+/, ''))
      })
    return null
  }
```
Vimeo's public oembed api provides the preview URL, e.g. `https://i.vimeocdn.com/video/21004662_295x166.webp`.
By removing the `_295x166` part we get the full size image.

#### Wikimedia
Easiest way I found:
``` tsx
    const seperator = '/commons/'
    const parts = src.split(seperator)
    const baseURL = parts[0]
    const filenameWithPath = parts[1]
    const filename = filenameWithPath.substring(
      filenameWithPath.lastIndexOf('/') + 1
    )
    const previewImageUrl = `${baseURL}${seperator}thumb/${filenameWithPath}/800px--${filename}.jpg`
```
[Video link](https://upload.wikimedia.org/wikipedia/commons/1/15/Inerter_vibration_isolation_experiment.webm) -> [Thumbnail link](https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Inerter_vibration_isolation_experiment.webm/1000px--Inerter_vibration_isolation_experiment.webm.jpg)
structure should be: 
`'upload.wikimedia.org/wikipedia/commons' + '/thumb' + '/1/15/{title}' + '/{size}px--{title}.jpg`

#### Geogebra 
This API call should provide us with the preview URL:
``` tsx
void fetch('https://www.geogebra.org/api/json.php', {
      method: 'POST',
      body: JSON.stringify({
        request: {
          '-api': '1.0.0',
          task: {
            '-type': 'fetch',
            fields: {
              field: [
                { '-name': 'width' },
                { '-name': 'height' },
                { '-name': 'preview_url' },
              ],
            },
            filters: {
              field: [{ '-name': 'id', '#text': id }],
            },
            limit: { '-num': '1' },
          },
        },
      }),
    })
```

**Comment by kulla** [comment]
@elbotho Do you only need the image or other meta data for the image as well (like the aspect ration)?

**Comment by elbotho** [comment]
@kulla I think image is enough.

**Comment by kulla** [comment]
@inyono What do you about the API: `assets.serlo.org/preview-image?iframe-url=<url>` which returns the preview image (or a default image when it was not found)

@elbotho Can you look for a default image which we shall use in case that there was an error or the preview image cannot be found?

**Comment by elbotho** [comment]
Sure! Placeholder png for empty results:
![preview_empty](https://user-images.githubusercontent.com/1258870/98814663-46cb0700-2426-11eb-925a-8b4640beea85.png)

**Comment by inyono** [comment]
> @inyono What do you about the API: `assets.serlo.org/preview-image?iframe-url=<url>` which returns the preview image (or a default image when it was not found)

I think we shouldn't use `assets.serlo.org` since that points to the Storage Bucket (although the Cloudflare Worker is in front and therefore we could override certain requests, I'd like to keep that exclusive to Google Cloud Storage). Maybe something like `thirdparty.serlo.org` or `embed.serlo.org`?

**Comment by elbotho** [comment]
@JacquesTa and @Ilaria-F the code from last Saturday is in [preview](https://github.com/serlo/serlo.org-cloudflare-worker/tree/preview). 
I'll add a fallback (`returnPlaceholder()`) for empty and not supported requests with the next commit,
then you can take over and incrementally build the features for the different providers.

**Comment by elbotho** [comment]
It's probably easier to use the URLs we build in the frontend, because they have a lot less variation:

- **YouTube:** `https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&html5=1…`
- **Geogegra:** `https://www.geogebra.org/material/iframe/id/${appletId}`
- **Wikimedia Commons:** `https://upload.wikimedia.org/wikipedia/commons/1/15/Inerter_vibration_isolation_experiment.webm`
- **Vimeo:** `https://player.vimeo.com/video/${id}?autoplay=1`
