### ISSUE TITLE
Redirect to correct instance

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-cloudflare-worker#70]
I found one additional special case that the legacy system currently handles (and that we probably want to have in the Cloudflare Worker in the long-term). Some UUIDs are instance-specific (e.g. entities). If you refer to an entity in the wrong instance, e.g. https://de.serlo.org/93321, you'll get redirected to the correct instance instead https://en.serlo.org/93321. Basically: in your current alias query, you should also get the instance (where applicable) and then possibly redirect to the correct instance. Currently, you'd have to do that for each type specifically (since `AbstractUuid` doesn't have an `instance` property), ping https://github.com/serlo/api.serlo.org/issues/131 as a follow-up (or preceding issue) that would simplify that.

**Comment by kulla** [comment]
Resolved by https://github.com/serlo/serlo.org-cloudflare-worker/pull/91 -> deployed in staging so that you can test it there.
