### ISSUE TITLE
Frontend resources get redirected

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#71]
When the frontend tries to load de.serlo-staging.dev/_next/static/Xi-6lAt8rBvyzVsDMDnU5/_ssgManifest.js, it gets redirected to https://de.serlo-staging.dev/mathe/5/mathe.

Related to https://github.com/serlo/serlo.org/pull/540

**Comment by inyono** [comment]
Okay, this is a two-fold bug:
- The regexp in the reworked alias system thinks this is a new alias (@inyono)
- The Cloudflare Worker doesn't recognize this is a frontend URL that should be resolved by the frontend (@kulla)

**Comment by inyono** [comment]
Fixed and deployed now (modulo caching). @kulla: feel free to create an issue for the second part that we discussed earlier if you want to approach that.
