### ISSUE TITLE
Allow notifications in new frontend for staging

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-cloudflare-worker#85]
Notifications are supported in the new frontend under `/user/notifications` but it seems the CF worker does not know about it and we end up with "Diese Seite existiert nicht!" in the legacy system.

**Steps (all with enabled frontend):**
- does not work: directly access https://de.serlo-staging.dev/user/notifications
- does work: navigate to notifications via menu (using client side redirect).
- does not work: refresh notifications page once you are there

**Comment by kulla** [comment]
@elbotho Am I right, that `de.serlo.org/user/notifications` needs to be redirected to `frontend.serlo.org/de/user/notifications`?

**Comment by elbotho** [comment]
yes, but only in staging for now.

**Comment by kulla** [comment]
@b Fixed in https://github.com/serlo/serlo.org-cloudflare-worker/pull/89 deployed in staging -> can you test it there?

**Comment by elbotho** [comment]
Perfect, thank you very much!

**Comment by kulla** [comment]
Let's wait for the code review (PR still needs to be merged) :smile:
