### ISSUE TITLE
Render license details in the new frontend

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#86]
See https://de.serlo-staging.dev/license/detail/1, the frontend should be ready, but it's somehow not working yet, also need to check CF worker.

**Comment by kulla** [comment]
Is it okay when this site renders in the new frontend also in production (for the ~10% of user in production who have the luck of getting the new frontend)?

**Comment by Entkenntnis** [comment]
Yes, this should be fine

**Comment by kulla** [comment]
@dal Fix in https://github.com/serlo/serlo.org-cloudflare-worker/pull/90 which is deployed in staging. There you can test it.

**Comment by Entkenntnis** [comment]
Thank you. We can then deploy to production with 25% Frontend
