### ISSUE TITLE
Frontend 25%: Update of supported types in production?

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#99]
Shall https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/wrangler.toml#L65 be updated for frontend 25% (ping @elbotho @dal )

**Comment by Entkenntnis** [comment]
I think it's fine.

**Comment by elbotho** [comment]
I'd wait for https://github.com/serlo/frontend/pull/656 personally.

**Comment by kulla** [comment]
> I think it's fine.

You mean the current list of supported types in production is fine?  Not that the list in staging ( https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/wrangler.toml#L43 ) is longer

**Comment by Entkenntnis** [comment]
Alright, I think we can sync the list, e.g. add GroupedExercise and Solution to production - this should be fine.

@elbotho, @kulla: What do you think about users? I'm hesitating a bit, because the new profil is missing a lot of information.

**Comment by elbotho** [comment]
Users is now (with comments) at the minimal configuration I discussed with Wolfgang, so it's fine.
